{"cells":[{"cell_type":"markdown","metadata":{"id":"jVGOHFL3W5hp"},"source":["En este archivo puedes escribir lo que estimes conveniente. Te recomendamos detallar tu solución y todas las suposiciones que estás considerando. Aquí puedes ejecutar las funciones que definiste en los otros archivos de la carpeta src, medir el tiempo, memoria, etc.\n","\n","PREPARACION:\n","1.   Commit inicial del proyecto (hecho con GitHub desktop)\n","3.   Instalar Git Flow con brew install git-flow\n","4.   Configurar repositorio con git flow init\n","5.   Configurar que los feature finish se hagan solo en develop con git config gitflow.feature.finish.keepremote true\n","6.   Sincronizar repositorio con GDrive\n","7.   Leer código desde GDrive con Colab"]},{"cell_type":"code","source":["# Project and dataset information\n","SOURCE_PATH = '/content/drive/Othercomputers/My Mac/latam-challenge'\n","PROJECT_ID = \"tw-techdash\"\n","DATASET_NAME = \"tweets_dataset\"\n","TABLE_NAME = \"tweets\"\n","BUCKET_NAME = 'tw-gcp-public-lab'\n","ZIP_FILE = \"tweets.json.zip\"\n","FILE_ID = '1ig2ngoXFTxP5Pa8muXo02mDTFexZzsis'\n","SOURCE_URI = f\"gs://{BUCKET_NAME}/raw/\""],"metadata":{"id":"g57ic23AMKFp","executionInfo":{"status":"ok","timestamp":1712288985964,"user_tz":180,"elapsed":2,"user":{"displayName":"Juan Herrera","userId":"01250943537373452870"}}},"execution_count":2,"outputs":[]},{"cell_type":"code","execution_count":36,"metadata":{"id":"fkniVfT9W5hr","executionInfo":{"status":"ok","timestamp":1712288880480,"user_tz":180,"elapsed":3,"user":{"displayName":"Juan Herrera","userId":"01250943537373452870"}}},"outputs":[],"source":["# Automatically reload the Jupyter kernel when it detects changes in the project directory\n","%reload_ext autoreload\n","\n","# IPython will attempt to automatically reload any module you've previously imported before executing a cell\n","%autoreload 2"]},{"cell_type":"code","source":["from google.colab import drive\n","\n","# Mount Google Drive to the path /content/drive\n","# Force remounting in case of errors or issues\n","drive.mount('/content/drive', force_remount=True)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"IV-79dMCpYAh","executionInfo":{"status":"ok","timestamp":1712288883318,"user_tz":180,"elapsed":2840,"user":{"displayName":"Juan Herrera","userId":"01250943537373452870"}},"outputId":"fdf6dbef-04d6-493f-9592-c15104564d57"},"execution_count":37,"outputs":[{"output_type":"stream","name":"stdout","text":["Mounted at /content/drive\n"]}]},{"cell_type":"code","execution_count":38,"metadata":{"id":"V_d7gErJW5hs","executionInfo":{"status":"ok","timestamp":1712288883616,"user_tz":180,"elapsed":300,"user":{"displayName":"Juan Herrera","userId":"01250943537373452870"}},"colab":{"base_uri":"https://localhost:8080/"},"outputId":"740b04d6-7d7f-4537-ddc2-1e493886f3fc"},"outputs":[{"output_type":"stream","name":"stdout","text":["shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n","    return _run_code(code, main_globals, None,\n","  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n","    exec(code, run_globals)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/__main__.py\", line 9, in <module>\n","    if sys.path[0] in (\"\", os.getcwd()):\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["# Import the necessary libraries in the virtual environment according to the requirements.txt file\n","# The purpose of this is to make the notebook work in any environment\n","import sys\n","!{sys.executable} -m pip install -r '{SOURCE_PATH}/requirements.txt'"]},{"cell_type":"code","execution_count":39,"metadata":{"id":"6iyOk2iaW5ht","executionInfo":{"status":"ok","timestamp":1712288883616,"user_tz":180,"elapsed":3,"user":{"displayName":"Juan Herrera","userId":"01250943537373452870"}}},"outputs":[],"source":["file_path = \"farmers-protest-tweets-2021-2-4.json\""]},{"cell_type":"code","execution_count":null,"metadata":{"id":"9hA7kAlIW5hu","colab":{"base_uri":"https://localhost:8080/"},"outputId":"eef964f6-a228-4f2f-f757-2bd1ca812800"},"outputs":[{"output_type":"stream","name":"stderr","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"output_type":"stream","name":"stdout","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-40-ef3161532441>\", line 1, in <cell line: 1>\n","    get_ipython().run_line_magic('cd', '{SOURCE_PATH}/src')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"<decorator-gen-85>\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in <lambda>\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]},{"output_type":"stream","name":"stderr","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"output_type":"stream","name":"stdout","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-40-ef3161532441>\", line 1, in <cell line: 1>\n","    get_ipython().run_line_magic('cd', '{SOURCE_PATH}/src')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"<decorator-gen-85>\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in <lambda>\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-40-ef3161532441>\", line 1, in <cell line: 1>\n","    get_ipython().run_line_magic('cd', '{SOURCE_PATH}/src')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"<decorator-gen-85>\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in <lambda>\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["%cd {SOURCE_PATH}/src"]},{"cell_type":"code","execution_count":40,"metadata":{"id":"PSagVvNPW5hu","executionInfo":{"status":"ok","timestamp":1712288883999,"user_tz":180,"elapsed":4,"user":{"displayName":"Juan Herrera","userId":"01250943537373452870"}},"colab":{"base_uri":"https://localhost:8080/"},"outputId":"0fe9ab16-5a97-4c09-bb2f-45ae13851017"},"outputs":[{"output_type":"stream","name":"stdout","text":["Ejecutando q1_time con file_path: farmers-protest-tweets-2021-2-4.json\n","[(datetime.date(2022, 1, 1), 'Registro 1'), (datetime.date(2022, 1, 2), 'Registro 2')]\n"]}],"source":["import q1_time\n","\n","# Llama a la función q1_time para obtener el resultado\n","resultado = q1_time.q1_time(file_path)\n","\n","# Imprime el resultado\n","print(resultado)"]},{"cell_type":"code","execution_count":4,"metadata":{"id":"pz4EZrB4W5hu","outputId":"80b849a9-0c58-4a77-d686-ed387ce94724","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1712289019576,"user_tz":180,"elapsed":16809,"user":{"displayName":"Juan Herrera","userId":"01250943537373452870"}}},"outputs":[{"output_type":"stream","name":"stdout","text":["Downloading 100%\n","Archivo subido a gs://tw-gcp-public-lab/raw/tweets.json.zip\n","Archivo descomprimido en gs://<Bucket: tw-gcp-public-lab>/raw/farmers-protest-tweets-2021-2-4.json\n"]}],"source":["from google.colab import auth\n","from googleapiclient.discovery import build\n","import io\n","from googleapiclient.http import MediaIoBaseDownload\n","from google.cloud import storage\n","import zipfile\n","\n","def authenticate_google_drive():\n","    \"\"\"Authenticates to Google Drive if needed.\"\"\"\n","    auth.authenticate_user()\n","\n","def download_file_from_drive(file_id):\n","    \"\"\"Downloads a file from Google Drive.\"\"\"\n","    drive_service = build('drive', 'v3')\n","    request = drive_service.files().get_media(fileId=file_id)\n","    downloaded = io.BytesIO()\n","    downloader = MediaIoBaseDownload(downloaded, request)\n","    done = False\n","    while done is False:\n","        status, done = downloader.next_chunk()\n","        print(f'Downloading {int(status.progress() * 100)}%')\n","    downloaded.seek(0)\n","    return downloaded\n","\n","def upload_file_to_cloud_storage(downloaded, bucket_name, folder_name):\n","    \"\"\"Uploads a file to Google Cloud Storage.\"\"\"\n","    client = storage.Client()\n","    bucket = client.bucket(bucket_name)\n","\n","    # Check and create folder\n","    if not bucket.blob(f\"{folder_name}/\"):\n","        bucket.blob(f\"{folder_name}/\").upload_from_string('', content_type='application/x-www-form-urlencoded;charset=UTF-8')\n","\n","    blob = bucket.blob(f'{folder_name}/{ZIP_FILE}')\n","    blob.upload_from_file(downloaded, content_type='application/zip')\n","    print(f'Archivo subido a gs://{bucket_name}/{blob.name}')\n","\n","    return client, bucket, blob\n","\n","def decompress_zip_file(downloaded, bucket, folder_name):\n","    \"\"\"Decompresses a ZIP file in Google Cloud Storage.\"\"\"\n","    try:\n","        with zipfile.ZipFile(downloaded, 'r') as z:\n","            for file_info in z.infolist():\n","                with z.open(file_info) as file:\n","                    blob_name = f'{folder_name}/{file_info.filename}'\n","                    blob = bucket.blob(blob_name)\n","                    blob.upload_from_file(file)\n","        print(f'Archivo descomprimido en gs://{bucket}/{blob_name}')\n","    except zipfile.BadZipFile:\n","        print(f'El archivo en gs://{bucket}/{folder_name}/ no es un archivo ZIP válido.')\n","    finally:\n","      return file_info.filename\n","\n","try:\n","    authenticate_google_drive()\n","    downloaded = download_file_from_drive(FILE_ID)\n","    client, bucket, blob = upload_file_to_cloud_storage(downloaded, 'tw-gcp-public-lab', 'raw')\n","    file_name = decompress_zip_file(downloaded, bucket, 'raw')\n","except Exception as e:\n","    print(f'Error: {e}')\n","finally:\n","    downloaded.close()  # Close downloaded file\n"]},{"cell_type":"code","source":["# TODO: ANALIZAR BORRAR ESTE BLOQUE\n","from google.cloud import bigquery\n","from google.api_core.exceptions import NotFound\n","\n","def authenticate_bigquery():\n","    \"\"\"Authenticates to BigQuery.\"\"\"\n","    return bigquery.Client(project=PROJECT_ID)\n","\n","def create_dataset_if_not_exists(client, dataset_name):\n","    \"\"\"Creates a dataset if it does not exist.\"\"\"\n","    dataset_ref = client.dataset(dataset_name)\n","    try:\n","        client.get_dataset(dataset_ref)\n","        print(f\"Dataset '{dataset_name}' already exists.\")\n","    except NotFound:\n","        client.create_dataset(dataset_ref)\n","        print(f\"Dataset '{dataset_name}' created.\")\n","\n","def create_table_if_not_exists(client, dataset_name, table_name, schema):\n","    \"\"\"Creates a table if it does not exist.\"\"\"\n","    dataset_ref = client.dataset(dataset_name)\n","    table_ref = dataset_ref.table(table_name)\n","    try:\n","        client.get_table(table_ref)\n","        print(f\"Table '{table_name}' already exists.\")\n","    except NotFound:\n","        table = bigquery.Table(table_ref, schema=schema)\n","        client.create_table(table)\n","        print(f\"Table '{table_name}' created.\")\n","\n","# Authenticate to BigQuery\n","client = authenticate_bigquery()\n","\n","# Define table schema\n","SCHEMA = [\n","    bigquery.SchemaField('created_at', 'STRING'),\n","    bigquery.SchemaField('username', 'STRING'),\n","    bigquery.SchemaField('text', 'STRING')\n","]\n","\n","# Create dataset if it does not exist\n","create_dataset_if_not_exists(client, DATASET_NAME)\n","\n","# Create table if it does not exist\n","create_table_if_not_exists(client, DATASET_NAME, TABLE_NAME, SCHEMA)\n","\n","# Load data from Cloud Storage to BigQuery\n","job_config = bigquery.LoadJobConfig()\n","job_config.source_format = bigquery.SourceFormat.NEWLINE_DELIMITED_JSON\n","job_config.write_disposition = bigquery.WriteDisposition.WRITE_TRUNCATE\n","\n","load_job = client.load_table_from_uri(\n","    SOURCE_URI+file_name,\n","    client.dataset(DATASET_NAME).table(TABLE_NAME),\n","    job_config=job_config\n",")\n","#load_job.result()  # Wait for the job to finish\n","print(f\"Data loaded from '{SOURCE_URI}' to table '{TABLE_NAME}'.\")\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"WLZnR3x3dZXB","executionInfo":{"status":"ok","timestamp":1712291059644,"user_tz":180,"elapsed":1399,"user":{"displayName":"Juan Herrera","userId":"01250943537373452870"}},"outputId":"ce6137c3-da9c-422f-d955-b4c36b7d3de8"},"execution_count":75,"outputs":[{"output_type":"stream","name":"stdout","text":["Dataset 'tweets_dataset' already exists.\n","Table 'tweets' already exists.\n","Data loaded from 'gs://tw-gcp-public-lab/raw/' to table 'tweets'.\n"]}]},{"cell_type":"code","source":["# TODO: ANALIZAR BORRAR ESTE BLOQUE\n","from google.cloud import storage\n","import json\n","\n","# Autenticar con Google Cloud Storage\n","storage_client = storage.Client()\n","\n","# Especificar la ubicación del archivo en GCS\n","bucket_name = \"tw-gcp-public-lab\"\n","file_name = \"raw/farmers-protest-tweets-2021-2-4.json\"\n","\n","# Obtener el archivo de GCS\n","bucket = storage_client.bucket(bucket_name)\n","blob = bucket.blob(file_name)\n","\n","# Leer el contenido del archivo JSON línea por línea\n","data = blob.download_as_string().decode('utf-8')\n","\n"],"metadata":{"id":"T0F06tSZoDqd","executionInfo":{"status":"ok","timestamp":1712288904791,"user_tz":180,"elapsed":5014,"user":{"displayName":"Juan Herrera","userId":"01250943537373452870"}}},"execution_count":43,"outputs":[]},{"cell_type":"code","source":["from google.cloud import bigquery\n","from google.api_core.exceptions import NotFound\n","\n","def authenticate_bigquery():\n","    \"\"\"Authenticates to BigQuery.\"\"\"\n","    return bigquery.Client(project=PROJECT_ID)\n","\n","def create_dataset_if_not_exists(client, dataset_name):\n","    \"\"\"Creates a dataset if it does not exist.\"\"\"\n","    dataset_ref = client.dataset(dataset_name)\n","    try:\n","        client.get_dataset(dataset_ref)\n","        print(f\"Dataset '{dataset_name}' already exists.\")\n","    except NotFound:\n","        client.create_dataset(dataset_ref)\n","        print(f\"Dataset '{dataset_name}' created.\")\n","\n","def create_table_if_not_exists(client, dataset_name, table_name):\n","    \"\"\"Creates a table if it does not exist.\"\"\"\n","    dataset_ref = client.dataset(dataset_name)\n","    table_ref = dataset_ref.table(table_name)\n","    try:\n","        client.get_table(table_ref)\n","        print(f\"Table '{table_name}' already exists.\")\n","    except NotFound:\n","        table = bigquery.Table(table_ref)\n","        table.schema = []  # Empty schema indicates that BigQuery should infer the schema\n","        client.create_table(table)\n","        print(f\"Table '{table_name}' created.\")\n","\n","# Authenticate to BigQuery\n","client = authenticate_bigquery()\n","\n","# Create dataset if it does not exist\n","create_dataset_if_not_exists(client, DATASET_NAME)\n","\n","# Create table if it does not exist\n","create_table_if_not_exists(client, DATASET_NAME, TABLE_NAME)\n","\n","# Load data from Cloud Storage to BigQuery\n","job_config = bigquery.LoadJobConfig()\n","job_config.source_format = bigquery.SourceFormat.NEWLINE_DELIMITED_JSON\n","job_config.autodetect = True  # Allow BigQuery to autodetect the schema\n","job_config.ignore_unknown_values = True  # Ignore unknown values in JSON\n","load_job = client.load_table_from_uri(\n","    SOURCE_URI+file_name,\n","    client.dataset(DATASET_NAME).table(TABLE_NAME),\n","    job_config=job_config\n",")\n","load_job.result()\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"teRz4l7jW-fq","executionInfo":{"status":"ok","timestamp":1712291097636,"user_tz":180,"elapsed":21827,"user":{"displayName":"Juan Herrera","userId":"01250943537373452870"}},"outputId":"9702abb5-a697-41e4-b4a0-f542b62559f7"},"execution_count":76,"outputs":[{"output_type":"stream","name":"stdout","text":["Dataset 'tweets_dataset' already exists.\n","Table 'tweets' already exists.\n"]},{"output_type":"execute_result","data":{"text/plain":["LoadJob<project=tw-techdash, location=US, id=469ad64f-ee7c-4861-a1d2-62ea4417bc1e>"]},"metadata":{},"execution_count":76}]},{"cell_type":"code","source":["query = \"\"\"\n","select user.profileBannerUrl\n","FROM {dataset}.{table}\n","limit 3\n","\"\"\".format(dataset=DATASET_NAME, table=TABLE_NAME)\n","\n","\n","query_job = client.query(query)\n","results = query_job.result()\n","#for row in results:\n","    #print(row)\n","for row in results:\n","    print(row)\n","    profile_banner_url = row[0]  # Acceder al primer elemento de la tupla\n","    print(profile_banner_url)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"WLlwchwVZqYx","executionInfo":{"status":"ok","timestamp":1712291146573,"user_tz":180,"elapsed":1137,"user":{"displayName":"Juan Herrera","userId":"01250943537373452870"}},"outputId":"120a0439-4119-4bc6-a7ce-39567f389e38"},"execution_count":78,"outputs":[{"output_type":"stream","name":"stdout","text":["Row(('https://pbs.twimg.com/profile_banners/873606662552268801/1595003990',), {'profileBannerUrl': 0})\n","https://pbs.twimg.com/profile_banners/873606662552268801/1595003990\n","Row(('https://pbs.twimg.com/profile_banners/1090885330163494914/1612202802',), {'profileBannerUrl': 0})\n","https://pbs.twimg.com/profile_banners/1090885330163494914/1612202802\n","Row(('https://pbs.twimg.com/profile_banners/819333425203150848/1614029794',), {'profileBannerUrl': 0})\n","https://pbs.twimg.com/profile_banners/819333425203150848/1614029794\n"]}]}],"metadata":{"kernelspec":{"display_name":"Python 3 (ipykernel)","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.6"},"colab":{"provenance":[]}},"nbformat":4,"nbformat_minor":0}